#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-jwt
Version  : 1.5.1
Release  : 9
URL      : https://rubygems.org/downloads/jwt-1.5.1.gem
Source0  : https://rubygems.org/downloads/jwt-1.5.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-echoe
BuildRequires : rubygem-rdoc

%description
No detailed description available

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n jwt-1.5.1
gem spec %{SOURCE0} -l --ruby > rubygem-jwt.gemspec

%build
gem build rubygem-jwt.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
jwt-1.5.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/jwt-1.5.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/jwt-1.5.1/Manifest
/usr/lib64/ruby/gems/2.3.0/gems/jwt-1.5.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/jwt-1.5.1/jwt.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/jwt-1.5.1/lib/jwt.rb
/usr/lib64/ruby/gems/2.3.0/gems/jwt-1.5.1/lib/jwt/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/jwt-1.5.1/spec/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/jwt-1.5.1/spec/jwt_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/jwt-1.5.1.gemspec
